[package]
name = "wordvec"
version = "0.1.0"
edition = "2024"
authors = ["SOFe <sofe2038@gmail.com>"]
license = "MIT"
description = "A compact `SmallVec<T>`-like container with only `align_of::<T>()` overhead for small stack-only instances."
categories = ["data-structures", "no-std"]
