name: Benchmark
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]

jobs:
  criterion:
    name: criterion
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{matrix.toolchain}}
      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cargo
            **/target/release
          key: ${{matrix.toolchain}}-${{hashFiles('**/Cargo.lock')}}-criterion
      - name: Run criterion
        run: cargo +${{matrix.toolchain}} bench --bench criterion
      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: criterion
          path: target/criterion
  iai:
    name: iai
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - run: sudo apt-get install -y valgrind
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{matrix.toolchain}}
      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cargo
            **/target/release
          key: ${{matrix.toolchain}}-${{hashFiles('**/Cargo.lock')}}-iai
      - run: mkdir -p target/iai
      - name: Run iai
        run: cargo +${{matrix.toolchain}} bench --bench iai >target/iai/summary.txt
      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: iai
          path: target/iai
  prepare-pages:
    name: Prepare GitHub pages
    runs-on: ubuntu-latest
    needs: [criterion, iai]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: criterion
          path: pages
      - uses: actions/download-artifact@v4
        with:
          name: iai
          path: pages/iai
      - run: tree pages
      - uses: actions/upload-pages-artifact@v3
        with:
          path: pages
  deploy-pages:
    name: Deploy GitHub pages
    runs-on: ubuntu-latest
    needs: [prepare-pages]
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    concurrency:
      group: gh-pages
      cancel-in-progress: true
    if: github.event_name == 'push' && (github.ref_type == 'tag' || (github.ref_type == 'branch' && github.ref_name == 'master'))
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
